openapi: 3.0.1
info:
  title: curso-cloud
  version: '1.0'
servers:
  - url: https://us-south.functions.appdomain.cloud/api/v1/web/edson.sensato%40espm.br_dev/default
security:
  - {}
paths:
  /analiseHumor:
    post:
      operationId: analiseHumor
      summary: analiseHumor
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              type: object
              properties:
                frase:
                  type: string
        required: false
      responses:
        '200':
          description: A successful invocation response
          content:
            application/json:
              schema:
                type: object
                properties:
                  humor:
                    type: boolean
                    example: true
